pipeline:
  test:
    image: node:alpine
    commands:
      - node -e "console.log('Actually run tests later');"
  build:
    image: docker
    commands:
      - docker build -t jallier/rtbackend:latest backend/
      - docker build -t jallier/rtfrontend:latest --build-arg REACT_APP_SERVER_HOST=listapi.jallier.xyz frontend/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
      event: push
  deploy:
    image: docker/compose:1.22.0
    commands:
      - docker-compose up -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - docker-compose.yml:/docker-compose.yml
    when:
      branch: master
      event: push
