version: '3.3'

services:
  maria:
    image: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rtlist
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  rtback:
    image: jallier/rtbackend:latest
    ports:
      - "3001:3001"
    depends_on:
      - maria
    restart: always
    environment:
      ENVIRONMENT: docker
  rtfront:
    image: jallier/rtfrontend:latest
    ports:
      - "5000:5000"
    depends_on:
      - rtback
    links:
      - rtback

volumes: 
  dbdata:
