version: '3.3'

services:
  maria:
    image: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rtlist
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
volumes: 
  dbdata:
